name: cafe_fermentacion
description: App de monitoreo de fermentación de café

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP
  http: ^1.2.0

  # Almacenamiento local (token de sesión)
  shared_preferences: ^2.3.0

  # Selección de imágenes (cámara / galería)
  image_picker: ^1.1.0

  # Gráficas (las que ya tienes funcionando)
  syncfusion_flutter_charts: ^26.1.35

  # Fechas en español
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true